function filePath = OpenVideoFile()
videoFilePath = fullfile(pwd, 'video\traffic.avi');
% [filename, pathname, filterindex] = uigetfile( ...
%     {  '*.avi','avi (*.avi)'; ...
%     '*.mp4','mp4 (*.mp4)'; ...
%     '*.MOV','MOV (*.MOV)'; ...
%     '*.*',  'all files (*.*)'}, ...
%     'MultiSelect', 'off', ...
%     videoFilePath);
[filename, pathname]=uigetfile('*');
filePath = 0;
if isequal(filename, 0) || isequal(pathname, 0)
    return;
end
filePath = fullfile(pathname, filename);
